version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - sharespace

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - sharespace
    deploy:
      replicas: 3  # This will scale the backend to 3 instances

  nginx:
    image: nginx:latest
    volumes:
      - ./backend/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf  # Mount the custom nginx.conf
    ports:
      - "8080:8080"  # Expose Nginx on port 8080
    depends_on:
      - backend
    networks:
      - sharespace

networks:
  sharespace:
    driver: bridge
