name: Deploy ShareSpace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up frontend environment variables
        run: |
          echo "VITE_SECRET_KEY=${{ secrets.VITE_SECRET_KEY }}" >> ./frontend/.env

      - name: Set up backend environment variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> ./backend/.env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> ./backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./backend/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./backend/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./backend/.env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> ./backend/.env
          echo "SERVICE_ACCOUNT_FILE=${{ secrets.SERVICE_ACCOUNT_FILE }}" >> ./backend/.env

      - name: Build and push backend image
        run: |
          pwd
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

      - name: Build and push frontend image
        run: |
          pwd
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            pwd
            cd /Users/ROHIT/ShareSpace
            docker-compose pull
            docker-compose down
            docker-compose up -d
